### PR TITLE
Support guess

### PR DESCRIPTION
**Pull request by yoshihara**
I implemented `guess` command. This command generated new config, so I also matched other methods to it.

Sorry, I'll refactor and add specs, but this PR is large already, please wait op minute...

### CODE REVIEW

**Comment by yoshihara** [comment]
@nahi oh, I forget something to need for `guess` command?

**Comment by nahi** [comment]
Ah, no, I saw you wrote "please wait' so I added that. Now it's ready? Please remove [WIP].

**Comment by yoshihara** [comment]
Oooh, I completed to implement `guess` command and this command works well (at least I think), but for more readable code, I think I should add some refactor and specs...refactor and specs is 'please wait', so Implementation is completed.

I remove [WIP].

**Comment by yoshihara** [comment]
This PR contains 'TODO' comment, I'll remove!

**Comment by uu59** [comment]
LGTM

**Pull request merged**
